title: "Demo floret vectors"
description: "Show how to train floret vectors and load them into a spaCy vectors model."
# Variables can be referenced across the project.yml using ${vars.var_name}
vars:
  name: "floret_vectors"
  lang: "en"
  oscar_dataset: "unshuffled_deduplicated_en"
  max_texts: 1000
  # number of processes (tokenization) and threads (floret)
  n_process: 8

# These are the directories that the project needs. The project CLI will make
# sure that they always exist.
directories: ["corpus", "software", "scripts", "vectors"]

# Assets that should be downloaded or available in the directory. We're shipping
# them with the project, so they won't have to be downloaded.
assets:
  - dest: "software/floret"
    git:
      repo: "https://github.com/explosion/floret"
      branch: "master"
      path: ""

## Workflows are sequences of commands (see below) executed in order. You can
## run them via "spacy project run [workflow]". If a commands's inputs/outputs
## haven't changed, it won't be re-run.
workflows:
  all:
    - compile-floret
    - tokenize-oscar
    - train-floret
    - init-ngram-vectors

# Project commands, specified in a style similar to CI config files (e.g. Azure
# pipelines). The name is the command name that lets you trigger the command
# via "spacy project run [command] [path]". The help message is optional and
# shown when executing "spacy project run [optional command] [path] --help".
commands:
  - name: "compile-floret"
    help: "Compile floret"
    script:
      - "make -C software/floret"
    outputs:
      - "software/floret/floret"

  - name: "tokenize-oscar"
    help: "Download, tokenize, and sentencize data"
    script:
      - "python scripts/tokenize_dataset.py ${vars.lang} ${vars.oscar_dataset} ${vars.max_texts} corpus/${vars.oscar_dataset}.${vars.max_texts}.tok.txt --n-process=${vars.n_process}"
    deps:
      - "scripts/tokenize_dataset.py"
    outputs:
      - "corpus/${vars.oscar_dataset}.${vars.max_texts}.tok.txt"

  - name: "train-floret"
    help: "Train floret vectors"
    script:
      - "software/floret/floret cbow -dim 300 -minCount 10 -minn 5 -maxn 6 -neg 10 -mode floret -hashCount 2 -bucket 20000 -thread ${vars.n_process} -input corpus/${vars.oscar_dataset}.${vars.max_texts}.tok.txt -output vectors/${vars.oscar_dataset}.${vars.max_texts}.dim300.minCount10.n5-6.neg10.modeFloret.hashCount2.bucket20000"
    deps:
      - "corpus/${vars.oscar_dataset}.${vars.max_texts}.tok.txt"
    outputs:
      - "vectors/${vars.oscar_dataset}.${vars.max_texts}.dim300.minCount10.n5-6.neg10.modeFloret.hashCount2.bucket20000.floret"
      - "vectors/${vars.oscar_dataset}.${vars.max_texts}.dim300.minCount10.n5-6.neg10.modeFloret.hashCount2.bucket20000.vec"
      - "vectors/${vars.oscar_dataset}.${vars.max_texts}.dim300.minCount10.n5-6.neg10.modeFloret.hashCount2.bucket20000.bin"

  - name: "init-ngram-vectors"
    help: "Create an ngram vectors model"
    script:
      - "python -m spacy init vectors ${vars.lang} vectors/${vars.oscar_dataset}.${vars.max_texts}.dim300.minCount10.n5-6.neg10.modeFloret.hashCount2.bucket20000.floret vectors/${vars.oscar_dataset}.${vars.max_texts}_ngram_model --mode floret" 
    deps:
      - "vectors/${vars.oscar_dataset}.${vars.max_texts}.dim300.minCount10.n5-6.neg10.modeFloret.hashCount2.bucket20000.floret"
    outputs:
      - "vectors/${vars.oscar_dataset}.${vars.max_texts}_ngram_model"

  - name: "floret-nn"
    help: "Demo floret vectors"
    script:
      - "software/floret/floret nn vectors/${vars.oscar_dataset}.${vars.max_texts}.dim300.minCount10.n5-6.neg10.modeFloret.hashCount2.bucket20000.bin"
    deps:
      - "vectors/${vars.oscar_dataset}.${vars.max_texts}.dim300.minCount10.n5-6.neg10.modeFloret.hashCount2.bucket20000.bin"

