title: "Demo floret vectors for Hungarian NER"
description: "Train floret vectors on OSCAR and compare default pruned vectors vs. floret vectors on NER for vector tables of the same size."
# Variables can be referenced across the project.yml using ${vars.var_name}
vars:
  name: "floret_hu_ner_demo"
  lang: "hu"
  oscar_dataset: "unshuffled_deduplicated_hu"
  max_texts: 500000
  vector_size: 50000
  vector_dim: 300
  n_process: 8
  treebank: "business_NER"
  gpu_id: -1

# These are the directories that the project needs. The project CLI will make
# sure that they always exist.
directories: ["assets", "configs", "corpus", "training", "metrics", "software", "training", "vectors"]

# Assets that should be downloaded or available in the directory. We're shipping
# them with the project, so they won't have to be downloaded.
assets:
  - dest: "software/floret"
    git:
      repo: "https://github.com/explosion/floret"
      branch: "master"
      path: ""
  - dest: "assets/business_NER"
    description: "Corpus of Business Newswire Texts from the Szeged Treebank"
    # url: https://rgai.inf.u-szeged.hu/node/130

## Workflows are sequences of commands (see below) executed in order. You can
## run them via "spacy project run [workflow]". If a commands's inputs/outputs
## haven't changed, it won't be re-run.
workflows:
  all:
    - compile-fasttext
    - tokenize-oscar
    - train-fasttext-standard-vectors
    - train-floret-vectors
    - init-standard-vectors
    - init-floret-vectors
    - create-config
    - convert
    - train-no-vectors
    - train-standard
    - train-floret
    - evaluate

# Project commands, specified in a style similar to CI config files (e.g. Azure
# pipelines). The name is the command name that lets you trigger the command
# via "spacy project run [command] [path]". The help message is optional and
# shown when executing "spacy project run [optional command] [path] --help".
commands:
  - name: "compile-fasttext"
    help: "Compile floret"
    script:
      - "make -C software/floret"
    # this doesn't really work, the no_skip bug fix is needed
    outputs:
      - "software/floret/floret"
    no_skip: true

  - name: "tokenize-oscar"
    help: "Download, tokenize, and sentencize data"
    script:
      - "python scripts/tokenize_dataset.py ${vars.lang} ${vars.oscar_dataset} ${vars.max_texts} corpus/${vars.oscar_dataset}.${vars.max_texts}.tok.txt --n-process=${vars.n_process}"
    deps:
      - "scripts/tokenize_dataset.py"
    outputs:
      - "corpus/${vars.oscar_dataset}.${vars.max_texts}.tok.txt"

  - name: "train-fasttext-standard-vectors"
    help: "Train fasttext standard vectors"
    script:
      - "software/floret/floret cbow -dim ${vars.vector_dim} -minCount 10 -minn 5 -maxn 6 -neg 10 -thread ${vars.n_process} -input corpus/${vars.oscar_dataset}.${vars.max_texts}.tok.txt -output vectors/${vars.oscar_dataset}.${vars.max_texts}.dim${vars.vector_dim}.minCount10.n5-6.neg10"
    deps:
      - "corpus/${vars.oscar_dataset}.${vars.max_texts}.tok.txt"
    outputs:
      - "vectors/${vars.oscar_dataset}.${vars.max_texts}.dim${vars.vector_dim}.minCount10.n5-6.neg10.vec"
      - "vectors/${vars.oscar_dataset}.${vars.max_texts}.dim${vars.vector_dim}.minCount10.n5-6.neg10.vec"

  - name: "train-floret-vectors"
    help: "Train floret vectors"
    script:
      - "software/floret/floret cbow -dim ${vars.vector_dim} -minCount 10 -minn 5 -maxn 6 -neg 10 -mode floret -hashCount 2 -bucket ${vars.vector_size} -thread ${vars.n_process} -input corpus/${vars.oscar_dataset}.${vars.max_texts}.tok.txt -output vectors/${vars.oscar_dataset}.${vars.max_texts}.dim${vars.vector_dim}.minCount10.n5-6.neg10.modeFloret.hashCount2.bucket${vars.vector_size}"
    deps:
      - "corpus/${vars.oscar_dataset}.${vars.max_texts}.tok.txt"
    outputs:
      - "vectors/${vars.oscar_dataset}.${vars.max_texts}.dim${vars.vector_dim}.minCount10.n5-6.neg10.modeFloret.hashCount2.bucket${vars.vector_size}.floret"
      - "vectors/${vars.oscar_dataset}.${vars.max_texts}.dim${vars.vector_dim}.minCount10.n5-6.neg10.modeFloret.hashCount2.bucket${vars.vector_size}.vec"
      - "vectors/${vars.oscar_dataset}.${vars.max_texts}.dim${vars.vector_dim}.minCount10.n5-6.neg10.modeFloret.hashCount2.bucket${vars.vector_size}.bin"

  - name: "init-standard-vectors"
    help: "Create a default vectors model"
    script:
      - "python -m spacy init vectors ${vars.lang} vectors/${vars.oscar_dataset}.${vars.max_texts}.dim${vars.vector_dim}.minCount10.n5-6.neg10.vec vectors/${vars.oscar_dataset}.${vars.max_texts}_standard_model --prune ${vars.vector_size}"
    deps:
      - "vectors/${vars.oscar_dataset}.${vars.max_texts}.dim${vars.vector_dim}.minCount10.n5-6.neg10.vec"
    outputs:
      - "vectors/${vars.oscar_dataset}.${vars.max_texts}_standard_model"

  - name: "init-floret-vectors"
    help: "Create a floret vectors model"
    script:
      - "python -m spacy init vectors ${vars.lang} vectors/${vars.oscar_dataset}.${vars.max_texts}.dim${vars.vector_dim}.minCount10.n5-6.neg10.modeFloret.hashCount2.bucket${vars.vector_size}.floret vectors/${vars.oscar_dataset}.${vars.max_texts}_floret_model --mode floret"
    deps:
      - "vectors/${vars.oscar_dataset}.${vars.max_texts}.dim${vars.vector_dim}.minCount10.n5-6.neg10.modeFloret.hashCount2.bucket${vars.vector_size}.floret"
    outputs:
      - "vectors/${vars.oscar_dataset}.${vars.max_texts}_floret_model"

  - name: "create-config"
    help: "Create a new config with an NER pipeline component"
    script:
      - "python -m spacy init config --lang ${vars.lang} --pipeline ner configs/config.cfg -o accuracy --force"
    outputs:
      - "configs/config.cfg"

  - name: "convert"
    help: "Convert the data to spaCy's format"
    script:
      - "mkdir -p corpus/${vars.treebank}"
      - "python scripts/preprocess_split_corpus.py assets/${vars.treebank}/hun_ner_corpus.txt corpus/${vars.treebank}/"
      - "python -m spacy convert corpus/${vars.treebank}/train.conll -c ner corpus/${vars.treebank}/ --n-sents 10"
      - "python -m spacy convert corpus/${vars.treebank}/dev.conll -c ner corpus/${vars.treebank}/ --n-sents 10"
      - "python -m spacy convert corpus/${vars.treebank}/test.conll -c ner corpus/${vars.treebank}/ --n-sents 10"
    deps:
      - "assets/${vars.treebank}/hun_ner_corpus.txt"
      - "scripts/preprocess_split_corpus.py"
    outputs:
      - "corpus/${vars.treebank}/train.spacy"
      - "corpus/${vars.treebank}/dev.spacy"
      - "corpus/${vars.treebank}/test.spacy"

  - name: "train-no-vectors"
    help: "Train the model without vectors"
    script:
      - "python -m spacy train configs/config.cfg --output training/${vars.treebank}-novectors/ --paths.train corpus/${vars.treebank}/train.spacy --paths.dev corpus/${vars.treebank}/dev.spacy --gpu-id ${vars.gpu_id} --initialize.vectors null --components.tok2vec.model.embed.include_static_vectors false"
    deps:
      - "configs/config.cfg"
      - "corpus/${vars.treebank}/train.spacy"
      - "corpus/${vars.treebank}/dev.spacy"
    outputs:
      - "training/${vars.treebank}-novectors/model-best"

  - name: "train-standard"
    help: "Train the model with default vectors"
    script:
      - "python -m spacy train configs/config.cfg --output training/${vars.treebank}.${vars.max_texts}-standard/ --paths.train corpus/${vars.treebank}/train.spacy --paths.dev corpus/${vars.treebank}/dev.spacy --gpu-id ${vars.gpu_id} --initialize.vectors vectors/${vars.oscar_dataset}.${vars.max_texts}_standard_model"
    deps:
      - "configs/config.cfg"
      - "corpus/${vars.treebank}/train.spacy"
      - "corpus/${vars.treebank}/dev.spacy"
      - "vectors/${vars.oscar_dataset}.${vars.max_texts}_standard_model"
    outputs:
      - "training/${vars.treebank}.${vars.max_texts}-standard/model-best"

  - name: "train-floret"
    help: "Train the model with floret vectors"
    script:
      - "python -m spacy train configs/config.cfg --output training/${vars.treebank}.${vars.max_texts}-floret/ --paths.train corpus/${vars.treebank}/train.spacy --paths.dev corpus/${vars.treebank}/dev.spacy --gpu-id ${vars.gpu_id} --initialize.vectors vectors/${vars.oscar_dataset}.${vars.max_texts}_floret_model"
    deps:
      - "configs/config.cfg"
      - "corpus/${vars.treebank}/train.spacy"
      - "corpus/${vars.treebank}/dev.spacy"
      - "vectors/${vars.oscar_dataset}.${vars.max_texts}_floret_model"
    outputs:
      - "training/${vars.treebank}.${vars.max_texts}-floret/model-best"

  - name: "evaluate"
    help: "Evaluate the models and export metrics"
    script:
      - "mkdir -p metrics/${vars.treebank}-novectors"
      - "python -m spacy evaluate training/${vars.treebank}-novectors/model-best corpus/${vars.treebank}/test.spacy --output metrics/${vars.treebank}-novectors/metrics.json --gpu-id ${vars.gpu_id}"
      - "mkdir -p metrics/${vars.treebank}.${vars.max_texts}-standard"
      - "python -m spacy evaluate training/${vars.treebank}.${vars.max_texts}-standard/model-best corpus/${vars.treebank}/test.spacy --output metrics/${vars.treebank}.${vars.max_texts}-standard/metrics.json --gpu-id ${vars.gpu_id}"
      - "mkdir -p metrics/${vars.treebank}.${vars.max_texts}-floret"
      - "python -m spacy evaluate training/${vars.treebank}.${vars.max_texts}-floret/model-best corpus/${vars.treebank}/test.spacy --output metrics/${vars.treebank}.${vars.max_texts}-floret/metrics.json --gpu-id ${vars.gpu_id}"
    deps:
      - "corpus/${vars.treebank}/test.spacy"
      - "training/${vars.treebank}-novectors/model-best"
      - "training/${vars.treebank}.${vars.max_texts}-standard/model-best"
      - "training/${vars.treebank}.${vars.max_texts}-floret/model-best"
    outputs:
      - "metrics/${vars.treebank}-novectors/metrics.json"
      - "metrics/${vars.treebank}.${vars.max_texts}-standard/metrics.json"
      - "metrics/${vars.treebank}.${vars.max_texts}-floret/metrics.json"
